---
# Ansible s'execute depuis node-1 : le groupe de securite n'ouvre aucun port
# d'administration vers l'exterieur et nous ne pouvons pas le modifier.
all:
  vars:
    ansible_user: ec2-user

  children:
    k3s_cluster:
      children:
        server:
          hosts:
            node-1:
              ansible_connection: local
              node_ip: 10.0.0.239
        agents:
          hosts:
            node-2:
              ansible_host: 10.0.0.55
              node_ip: 10.0.0.55
            node-3:
              ansible_host: 10.0.0.4
              node_ip: 10.0.0.4
