---
all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

  children:
    k3s_cluster:
      children:
        server:
          hosts:
            node-1:
              ansible_host: 52.28.139.102
              node_ip: 10.0.0.239
              instance_id: i-053b2016e9a5dc459
        agents:
          hosts:
            node-2:
              ansible_host: 10.0.0.55
              node_ip: 10.0.0.55
              instance_id: i-0402d50c33a35cf19
            node-3:
              ansible_host: 10.0.0.4
              node_ip: 10.0.0.4
              instance_id: i-029a3af4299b00e26
          vars:
            # Les workers n'ont pas d'IP publique stable, on rebondit sur node-1.
            ansible_ssh_common_args: >-
              -o ProxyJump={{ hostvars['node-1'].ansible_user }}@{{ hostvars['node-1'].ansible_host }}
              -o StrictHostKeyChecking=no
