---
- name: Autoriser les cles publiques declarees
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item.key }}"
    state: present
  loop: "{{ ssh_public_keys }}"
  loop_control:
    label: "{{ item.name }}"
